### ISSUE TITLE
Fix color grading on GLSL ES platforms

### ISSUE THREAD

**Issue by kraifpatrik** [blueburncz/BBMOD#38]
![image](https://user-images.githubusercontent.com/9461391/180720769-2c3cdef5-92e2-4727-90ff-72db68ad603f.png)

**Comment by slojanko** [comment]
Got this on Chrome Version 105.0.5195.102 (Official Build) (64-bit) running with AMD iGPU.

**Comment by kraifpatrik** [comment]
When I disable post processing effects I don't get this visual bug anymore, at least on Safari. I will try to figure out what exactly causes the issue in the post processing shader.

**Comment by kraifpatrik** [comment]
Alright, it's the color grading through LUT shader.

**Comment by kraifpatrik** [comment]
I've tried multiple things, which did reduce the artifacts to some extent, but they did not disappear completely. Hence I'm disabling color grading for GLSL ES platforms. Commit here a2904f5d9c174b5a3c20f027ba9ec03234c6277b
