### ISSUE TITLE
Mixamo issues

### ISSUE THREAD

**Issue by kraifpatrik** [blueburncz/BBMOD#8]
When uploading a custom character to [Mixamo](https://www.mixamo.com/) and downloading it animated as FBX, BBMOD CLI crashes during animation conversion. DAE does get converted, but the animation is broken (model is distorted). ~~This seems to be dependent on the file format of the uploaded character - FBX has the issues described, but OBJ is working perfectly fine.~~ This is likely an issue with [Assimp](https://github.com/assimp/assimp), as the animations work properly in Blender.

**Comment by kraifpatrik** [comment]
Fixed the crash during FBX conversion in 2906e8114ff144fd92fc36db100cedb82c0357d9, but converted animations have the same issues as DAE.

**Comment by kraifpatrik** [comment]
Related issue in Assimp: https://github.com/assimp/assimp/issues/1974

**Comment by kraifpatrik** [comment]
Based on experience of other users, uploading an OBJ to Mixamo doesn't always resolve the problem + DAE files work properly.

**Comment by karlforshaw** [comment]
Has there been any progress on this? I'm having a really hard time trying to figure out what I need to do to work around it.

**Comment by kraifpatrik** [comment]
I've just tried setting `AI_CONFIG_IMPORT_FBX_PRESERVE_PIVOTS` to `false` again (it was commented out) and a Mixamo FBX finally loaded correctly! Commit b6a17ad5d98f4c59a5226f69b3e82414efc038b2
